SERVER_IP="165.194.35.203"
SERVER_HTTP_URL="nsl3.cau.ac.kr"
#UE_IFACE="wlp5s0"   # wifi
UE_IFACE="enp2s0"  # ethernet
SERVER_IFACE="enp0s31f6"

DURATION=300
PING_INTERVAL=0.2
HTTP_INTERVAL=0.5
SS_INTERVAL=0.2
IFACE_INTERVAL=1

TCPDUMP_SNAPLEN=128
LOG_ROOT="./logs"
TMP_ROOT="./tmp"