SERVER_IP="165.194.35.203"
SERVER_HTTP_URL="nsl3.cau.ac.kr"
SERVER_PORT="20075"
LOCAL_IP="192.168.1.150"
#UE_IFACE="wlp5s0"   # wifi
#UE_IFACE="enp2s0"  # ethernet
STARLINK_IFACE="enx588694fda289"
SERVER_IFACE="enp0s31f6"

DURATION=300
# PING_INTERVAL=0.2
HTTP_INTERVAL=0.05
SS_INTERVAL=0.01
IFACE_INTERVAL=0.1
IPERF_INTERVAL=0.5

TCPDUMP_SNAPLEN=128
LOG_ROOT="./logs"
TMP_ROOT="./tmp"
